extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false

  # Indentation (2 spaces is standard for YAML)
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
  comments-indentation: {}

  # Document start (---) is optional
  document-start: disable

  # Truthy values (true/false vs yes/no)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Key ordering
  key-ordering: disable

  # Trailing spaces
  trailing-spaces: {}

  # New line at end of file
  new-line-at-end-of-file: {}

# Ignore patterns
ignore: |
  .git/
  node_modules/
  venv/
  .venv/
  env/
  .env/
  __pycache__/
  *.pyc
  build/
  dist/
